node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        app = docker.build('tsukahara0814/devops_sample_nodejs')
    }

    stage('Test') {
        // app.inside {
        sh 'npm install --only=dev'
        sh 'npm test'
        // }
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
            app.push("latest")
        }
    }
}